"use client";

import { useEffect, useMemo, useState } from "react";
import { Search, SlidersHorizontal, ArrowUpRight, ChevronLeft, ChevronRight, MoreHorizontal, Send, Eye, Pencil, Copy, Trash2, Download, Mail, X, ArrowDown } from "lucide-react";
import type { Customer, Quote, QuoteStatus, ShareChannel } from "@/lib/types";
import { formatDate, money } from "@/lib/utils";
import { Avatar, EmptyState, StatusBadge, WhatsAppIcon } from "./ui";

type Props = {
  quotes: Quote[]; customers: Customer[]; compact?: boolean;
  filter: QuoteStatus | "all"; onFilter: (filter: QuoteStatus | "all") => void;
  onDetail: (quote: Quote) => void; onEdit: (quote: Quote) => void; onShare: (quote: Quote, channel?: ShareChannel) => void;
  onDuplicate: (quote: Quote) => void; onDelete: (quote: Quote) => void; onPdf: (quote: Quote) => void;
  onStatus: (quote: Quote, status: QuoteStatus) => void;
  onExport: (quotes: Quote[]) => void; onNew: () => void; onAll?: () => void;
};

export function QuoteTable({ quotes, customers, compact = false, filter, onFilter, onDetail, onEdit, onShare, onDuplicate, onDelete, onPdf, onStatus, onExport, onNew, onAll }: Props) {
  const [search, setSearch] = useState("");
  const [showFilters, setShowFilters] = useState(false);
  const [customerFilter, setCustomerFilter] = useState("");
  const [sort, setSort] = useState("newest");
  const [page, setPage] = useState(1);
  const [menu, setMenu] = useState<{ quote: Quote; top: number; left: number } | null>(null);
  const pageSize = compact ? 5 : 10;
  const filtered = useMemo(() => {
    const query = search.toLocaleLowerCase("es");
    const result = quotes.filter((quote) => {
      const customer = customers.find((item) => item.id === quote.customerId);
      return (filter === "all" || quote.status === filter) && (!customerFilter || quote.customerId === Number(customerFilter)) && `${quote.number} ${quote.title} ${customer?.name} ${customer?.contact}`.toLocaleLowerCase("es").includes(query);
    });
    return result.sort((a, b) => sort === "amount" ? b.totalCents - a.totalCents : sort === "oldest" ? a.issueDate.localeCompare(b.issueDate) || a.id - b.id : b.issueDate.localeCompare(a.issueDate) || b.createdAt.localeCompare(a.createdAt));
  }, [quotes, customers, filter, customerFilter, search, sort]);
  useEffect(() => { setPage(1); }, [filter, customerFilter, search, sort]);
  useEffect(() => {
    const close = () => setMenu(null);
    const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") close(); };
    window.addEventListener("resize", close); window.addEventListener("scroll", close, true); window.addEventListener("keydown", keydown);
    return () => { window.removeEventListener("resize", close); window.removeEventListener("scroll", close, true); window.removeEventListener("keydown", keydown); };
  }, []);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const currentPage = Math.min(page, totalPages);
  const visible = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const tabs: { key: QuoteStatus | "all"; label: string }[] = [{ key: "all", label: "Todas" }, { key: "draft", label: "Borradores" }, { key: "sent", label: "Enviadas" }, { key: "review", label: "Revisión" }, { key: "accepted", label: "Aprobadas" }, { key: "rejected", label: "Rechazadas" }, { key: "archived", label: "Archivadas" }];
  const menuAction = (action: (quote: Quote) => void) => { if (menu) action(menu.quote); setMenu(null); };
  return <section className="card quotes-card" id="cotizaciones"><div className="quotes-card-heading"><div className="heading-with-count"><h2>{compact ? "Cotizaciones recientes" : "Todas tus cotizaciones"}</h2><span className="count-pill">{quotes.length}</span></div>{compact ? <button className="text-button" onClick={onAll}>Ver todas las cotizaciones<ArrowUpRight size={15} /></button> : <button className="button button-secondary button-sm" onClick={() => onExport(filtered)}><Download size={15} />Exportar CSV</button>}</div><div className="table-toolbar"><div className="table-tabs" role="tablist" aria-label="Estado de cotización">{tabs.map((tab) => <button key={tab.key} role="tab" aria-selected={filter === tab.key} className={filter === tab.key ? "active" : ""} onClick={() => onFilter(tab.key)}>{tab.label}<span>{tab.key === "all" ? quotes.length : quotes.filter((quote) => quote.status === tab.key).length}</span></button>)}</div><div className="table-search-tools"><div className="search-field"><Search size={16} /><input aria-label="Buscar cotización" placeholder="Buscar cotización..." value={search} onChange={(event) => setSearch(event.target.value)} />{search && <button className="search-clear" onClick={() => setSearch("")} aria-label="Limpiar búsqueda"><X size={13} /></button>}</div><button className={`icon-button filter-button ${showFilters || customerFilter ? "selected" : ""}`} aria-label="Mostrar filtros" aria-expanded={showFilters} onClick={() => setShowFilters(!showFilters)}><SlidersHorizontal size={16} /></button></div></div>{showFilters && <div className="expanded-filters"><label>Cliente<select value={customerFilter} onChange={(event) => setCustomerFilter(event.target.value)}><option value="">Todos los clientes</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><label>Ordenar por<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Más recientes</option><option value="oldest">Más antiguas</option><option value="amount">Mayor importe</option></select></label><button className="text-button" onClick={() => { setCustomerFilter(""); setSort("newest"); setSearch(""); onFilter("all"); }}>Limpiar filtros<X size={13} /></button></div>}<div className="table-scroll"><table className="quotes-table"><thead><tr><th>Cotización</th><th>Cliente</th><th><span>Fecha<ArrowDown size={11} /></span></th><th className="amount-cell">Importe</th><th>Estado</th><th className="channels-cell">Envío</th><th aria-label="Acciones" /></tr></thead><tbody>{visible.map((quote) => {
    const customer = customers.find((item) => item.id === quote.customerId);
    return <tr key={quote.id}><td><button className="quote-title-cell" onClick={() => onDetail(quote)}><strong>{quote.number}</strong><span title={quote.title}>{quote.title}</span></button></td><td><div className="customer-cell"><Avatar name={customer?.name ?? "Cliente"} color={customer?.color} small /><div><strong>{customer?.name ?? "Cliente"}</strong><span>{customer?.contact}</span></div></div></td><td className="date-cell">{formatDate(quote.issueDate, true)}</td><td className="amount-cell"><strong>{money(quote.totalCents, quote.currency)}</strong></td><td><label className="status-picker"><StatusBadge status={quote.status} /><select aria-label={`Cambiar estado de ${quote.number}`} value={quote.status} onChange={(event) => onStatus(quote, event.target.value as QuoteStatus)}><option value="draft">Borrador</option><option value="sent">Enviada</option><option value="accepted">Aceptada</option><option value="expired">Vencida</option></select></label></td><td><div className="channel-buttons"><button aria-label={`Compartir ${quote.number} por WhatsApp`} title="Compartir por WhatsApp" className={`channel-icon whatsapp ${quote.sharedVia.includes("whatsapp") ? "used" : ""}`} onClick={() => onShare(quote, "whatsapp")}><WhatsAppIcon size={17} /></button><button aria-label={`Compartir ${quote.number} por correo`} title="Compartir por correo" className={`channel-icon email ${quote.sharedVia.includes("email") ? "used" : ""}`} onClick={() => onShare(quote, "email")}><Mail size={16} /></button></div></td><td><div className="row-actions"><button className="icon-button row-send" title="Enviar cotización" aria-label={`Enviar ${quote.number}`} onClick={() => onShare(quote)}><Send size={15} /></button><button className="icon-button" aria-label={`Acciones de ${quote.number}`} aria-expanded={menu?.quote.id === quote.id} onClick={(event) => { const rect = event.currentTarget.getBoundingClientRect(); setMenu(menu?.quote.id === quote.id ? null : { quote, top: Math.min(rect.bottom + 5, window.innerHeight - 278), left: Math.max(12, rect.right - 208) }); }}><MoreHorizontal size={18} /></button></div></td></tr>;
  })}</tbody></table></div>{!visible.length && <EmptyState title={quotes.length ? "No encontramos cotizaciones" : undefined} description={quotes.length ? "Prueba con otra búsqueda o cambia los filtros seleccionados." : undefined} onAction={quotes.length ? () => { setSearch(""); onFilter("all"); setCustomerFilter(""); } : onNew} action={quotes.length ? "Limpiar filtros" : "Nueva cotización"} />}<div className="table-footer"><span>Mostrando <strong>{filtered.length ? (currentPage - 1) * pageSize + 1 : 0}–{Math.min(currentPage * pageSize, filtered.length)}</strong> de <strong>{filtered.length}</strong> cotizaciones</span><div className="pagination"><button className="icon-button" disabled={currentPage <= 1} aria-label="Página anterior" onClick={() => setPage(currentPage - 1)}><ChevronLeft size={16} /></button><span>{currentPage}<span> / {totalPages}</span></span><button className="icon-button" disabled={currentPage >= totalPages} aria-label="Página siguiente" onClick={() => setPage(currentPage + 1)}><ChevronRight size={16} /></button></div></div>{menu && <><div className="menu-dismiss" onClick={() => setMenu(null)} /><div className="action-menu" role="menu" style={{ top: menu.top, left: menu.left }}><button role="menuitem" onClick={() => menuAction(onDetail)}><Eye size={15} />Ver cotización</button><button role="menuitem" disabled={menu.quote.status === "accepted"} onClick={() => menuAction(onEdit)}><Pencil size={15} />Editar cotización</button><button role="menuitem" onClick={() => menuAction(onShare)}><Send size={15} />Enviar cotización</button>{menu.quote.status !== "sent" && <button role="menuitem" onClick={() => menuAction((item) => onStatus(item, "sent"))}><Send size={15} />Marcar como enviada</button>}{menu.quote.status !== "accepted" && <button role="menuitem" onClick={() => menuAction((item) => onStatus(item, "accepted"))}><Eye size={15} />Marcar como aceptada</button>}<button role="menuitem" onClick={() => menuAction(onDuplicate)}><Copy size={15} />Duplicar</button><button role="menuitem" onClick={() => menuAction(onPdf)}><Download size={15} />Descargar PDF</button><hr /><button role="menuitem" className="danger-text" onClick={() => menuAction(onDelete)}><Trash2 size={15} />Eliminar cotización</button></div></>}</section>;
}
